## 对每个房源进行评分

In [3]:
import pandas as pd
import numpy as np
from bokeh.core.property import include

In [4]:
df = pd.read_csv('北京市租房数据集.csv',encoding='gbk')
df.head(5)

,编号,标题,区域,街道,小区,租金,面积,单价（每平米租金）,户型,卧室数量,...,距地铁距离,是否有学校,是否有医院,是否有商场,图片链接,纬度,经度,发布日期,状态,创建时间
0,1,西城区月坛丰汇园一居整租,西城区,月坛,丰汇园,12416,51.1,242.97,一居,1,...,3.4,0,1,1,/static/images/house5.jpg,39.915675,116.378961,2025/12/19,1,46:56.4
1,2,西城区西单报国寺小区四居及以上整租,西城区,西单,报国寺小区,9492,109.5,86.68,四居及以上,4,...,0.3,0,1,1,/static/images/house6.jpg,39.932850,116.372224,2024/2/14,1,46:56.4
2,3,西城区西单西便门东里四居及以上整租,西城区,西单,西便门东里,14731,116.5,126.45,四居及以上,4,...,0.4,1,0,0,/static/images/house6.jpg,39.933989,116.358808,2025/4/9,1,46:56.4
3,4,西城区广安门西便门东里三居整租,西城区,广安门,西便门东里,8702,86.5,100.60,三居,3,...,1.0,0,1,1,/static/images/house2.jpg,39.923077,116.386571,2024/2/27,1,46:56.4
4,5,西城区广安门广外南街一居合租,西城区,广安门,广外南街,2503,11.0,227.55,一居,1,...,1.4,1,1,1,/static/images/house2.jpg,39.935869,116.359964,2024/8/12,1,46:56.4

复制一份数据进行打分

In [5]:
df_score = df.copy()
df_score.head(5)

,编号,标题,区域,街道,小区,租金,面积,单价（每平米租金）,户型,卧室数量,...,距地铁距离,是否有学校,是否有医院,是否有商场,图片链接,纬度,经度,发布日期,状态,创建时间
0,1,西城区月坛丰汇园一居整租,西城区,月坛,丰汇园,12416,51.1,242.97,一居,1,...,3.4,0,1,1,/static/images/house5.jpg,39.915675,116.378961,2025/12/19,1,46:56.4
1,2,西城区西单报国寺小区四居及以上整租,西城区,西单,报国寺小区,9492,109.5,86.68,四居及以上,4,...,0.3,0,1,1,/static/images/house6.jpg,39.932850,116.372224,2024/2/14,1,46:56.4
2,3,西城区西单西便门东里四居及以上整租,西城区,西单,西便门东里,14731,116.5,126.45,四居及以上,4,...,0.4,1,0,0,/static/images/house6.jpg,39.933989,116.358808,2025/4/9,1,46:56.4
3,4,西城区广安门西便门东里三居整租,西城区,广安门,西便门东里,8702,86.5,100.60,三居,3,...,1.0,0,1,1,/static/images/house2.jpg,39.923077,116.386571,2024/2/27,1,46:56.4
4,5,西城区广安门广外南街一居合租,西城区,广安门,广外南街,2503,11.0,227.55,一居,1,...,1.4,1,1,1,/static/images/house2.jpg,39.935869,116.359964,2024/8/12,1,46:56.4

1.租金评分

In [6]:
df_score['租金评分'] = pd.qcut(df_score['租金'].rank(method='first'),q=5,labels=[5,4,3,2,1]).astype(int)

2.面积评分

In [7]:
df_score['面积评分'] = pd.qcut(df_score['面积'].rank(method='first'),q=5,labels=[1,2,3,4,5]).astype(int)

3.配套评分（房源周围是否有地铁、学校、医院、商场）

In [8]:
df_score['配套评分'] = (
    df_score['是否有地铁'].apply(lambda x: 1 if x == 1 else 0) +
    df_score['是否有学校'].apply(lambda x: 1 if x == 1 else 0) +
    df_score['是否有医院'].apply(lambda x: 1 if x == 1 else 0) +
    df_score['是否有商场'].apply(lambda x: 1 if x == 1 else 0)
)
df_score['配套分'] = pd.cut(df_score['配套评分'],bins=[0,1,2,3,4,5],labels=[1,2,3,4,5],include_lowest=True).astype(int)
df_score.tail()

,编号,标题,区域,街道,小区,租金,面积,单价（每平米租金）,户型,卧室数量,...,图片链接,纬度,经度,发布日期,状态,创建时间,租金评分,面积评分,配套评分,配套分
35077,35078,顺义区李桥空港花园一居合租,顺义区,李桥,空港花园,631,13.1,48.17,一居,1,...,/static/images/house2.jpg,40.104202,116.645747,2024/5/4,1,46:57.4,5,1,4,4
35078,35079,顺义区天竺天竺花园二居合租,顺义区,天竺,天竺花园,501,17.4,28.79,二居,2,...,/static/images/house6.jpg,40.128501,116.655499,2025/10/5,1,46:57.4,5,2,4,4
35079,35080,顺义区天竺石园小区二居合租,顺义区,天竺,石园小区,451,22.7,19.87,二居,2,...,/static/images/house2.jpg,40.118863,116.665502,2024/10/25,1,46:57.4,5,3,3,3
35080,35081,顺义区空港裕龙花园一居合租,顺义区,空港,裕龙花园,633,12.9,49.07,一居,1,...,/static/images/house2.jpg,40.108934,116.642426,2025/11/24,1,46:57.4,5,1,2,2
35081,35082,顺义区空港空港花园四居及以上合租,顺义区,空港,空港花园,841,16.8,50.06,四居及以上,4,...,/static/images/house3.jpg,40.100155,116.667022,2025/3/15,1,46:57.4,5,2,3,3

4.装修评分

In [9]:
df_score['装修情况'].unique()
mapping = {'精装':5,'简装':3,'毛坯':1}
df_score['装修评分'] = df_score['装修情况'].map(mapping).fillna(3).astype(int)

5.楼层评分

In [10]:
df_score['所在楼层'].unique()
Floor = {'低楼层':1,'高楼层':1,'中楼层':5}
df_score['楼层评分'] = df_score['所在楼层'].map(Floor).fillna(1).astype(int)

性价比总分

In [11]:
df_score['性价比总分'] = (
    df_score['租金评分'] * 0.3 +
    df_score['面积评分'] * 0.2 +
    df_score['配套评分'] * 0.2 +
    df_score['装修评分'] * 0.15 +
    df_score['楼层评分'] * 0.15
)
df_score['性价比总分'].unique()

array([1.6, 2.8, 2. , 2.8, 1.6, 3.1, 2.6, 2.7, 2.2, 2.7, 2.9, 3.2, 1.9,
       2.4, 1.8, 3.5, 3. , 3. , 2.2, 2.6, 3.1, 1.4, 2.1, 2.9, 2.5, 2.3,
       2.5, 2.1, 3.7, 2.3, 2. , 1.9, 3.4, 1.8, 1.7, 2.9, 1.4, 1.5, 2.4,
       1.8, 2.3, 1.9, 3.3, 3.4, 1.1, 3.2, 3. , 1.6, 2.4, 3.6, 1.7, 2. ,
       3.3, 1.3, 1.5, 3.9, 3.6, 1.2, 3.6, 4.1, 3.8, 4.2, 4. , 3.8, 4.1,
       3.5, 4.4, 3.9, 4.5, 4.3, 3.7, 4.3])

## 每个区域性价比总分的前三位

In [12]:
top_value = df_score.sort_values('性价比总分',ascending=False).groupby('区域').head(3)
top_value[['标题','区域','租金','面积','租金评分','面积评分','性价比总分']]

                         标题    区域    租金     面积  租金评分  面积评分  性价比总分
24317    通州区新华大街通州万达四居及以上整租   通州区  2101  140.8     4     5    4.5
30749        昌平区霍营沙河高教园二居合租   昌平区  1122   23.6     5     3    4.4
32182        顺义区顺义城莲竹花园一居合租   顺义区   658   24.9     5     3    4.4
24498         通州区梨园梨园小镇一居合租   通州区   994   24.2     5     3    4.4
23864    通州区新华大街通州万达四居及以上合租   通州区  1187   24.6     5     3    4.4
19206        石景山区模式口西黄村三居合租  石景山区   928   22.1     5     3    4.4
34819      顺义区石园空港花园四居及以上整租   顺义区  1884  116.8     4     5    4.3
32116      顺义区空港裕龙花园四居及以上整租   顺义区  1826  137.5     4     5    4.3
26465  大兴区生物医药基地绿地启航四居及以上整租   大兴区  2036  147.8     4     5    4.3
27879     大兴区生物医药基地绿地启航三居整租   大兴区  2097  124.4     4     5    4.3
28156         昌平区龙泽天通苑北三居合租   昌平区  1168   23.2     5     3    4.2
26756     大兴区枣园天宫院小区四居及以上整租   大兴区  2435  108.4     3     5    4.2
20108     石景山区金顶街中铁建四居及以上整租  石景山区  3578  104.1     3     5    4.2
28091      昌平区沙河龙域北街四居及以上合租   昌平区   641   23.4     5     3    4.2
19896    石景山区模式口古城南路四居及以上合租  石景山区   818   23.1     5     3    4.2
14677      丰台区角门角门东里四居及以上合租   丰台区  1012   21.9     5     3    4.2
14456       丰台区总部基地怡海花园二居合租   丰台区   821   20.1     5     2    4.2
11038      朝阳区望京三里屯嘉铭中心二居合租   朝阳区  1131   24.9     5     3    4.2
11282     朝阳区亚运村国贸公寓四居及以上整租   朝阳区  3524  131.3     3     5    4.2
11814         朝阳区国贸润泽公馆一居合租   朝阳区  1189   22.2     5     3    4.2
15590        丰台区方庄马家堡东路三居合租   丰台区  1051   23.6     5     3    4.2
2361        西城区什刹海报国寺小区三居合租   西城区  1603   22.5     4     3    4.1
8934       海淀区上地上地西里四居及以上合租   海淀区  1626   22.9     4     3    4.1
2328        西城区广安门三里河一区一居合租   西城区  1661   21.8     4     2    3.9
7567          海淀区知春路知春里三居合租   海淀区  1366   21.6     4     2    3.9
7925         海淀区学院路上地西里三居整租   海淀区  4832  103.9     2     5    3.9
4454         东城区王府井南锣鼓巷三居合租   东城区  1500   22.0     4     3    3.9
2714        西城区展览路报国寺小区三居合租   西城区  1505   23.2     4     3    3.9
3839      东城区王府井南锣鼓巷四居及以上合租   东城区  1973   18.2     4     2    3.9
3748        东城区东直门东四北大街三居合租   东城区  1595   22.1     4     3    3.9

从性价比总分排序结果来看，性价比最高的房源主要集中于通州、大兴、顺义等外围区域，且普遍以“低租金、大面积”的整租或合租户型为主（综合得分达4.5分）；而东城、西城、海淀、朝阳等核心城区虽然地段优越，但因租金评分被大幅拉低，整体性价比得分普遍在3.9至4.1分之间，处于榜单中下游，反映出北京租房市场存在显著的“核心区租金溢价”现象。

In [14]:
df_score.to_excel('房源性价比评分.xlsx',index=False)

ModuleNotFoundError: No module named 'openpyxl'